greenplum-db/GreenplumPython

greenplumpython/__init__.py, greenplumpython/expr.py, greenplumpython/func.py, greenplumpython/table.py, tests/test_const_table.py, tests/test_db.py, tests/test_func.py
Being able to call functions is essential for data analytics. This
patch adds support for calling functions in Greenplum. Given
that Column is not completed when the work starts, this patch
only implements function calls on constants but not on
tables. Changes are required to support function calls on tables.
=> Support function calls on constants

greenplumpython/expr.py, greenplumpython/func.py, greenplumpython/table.py, greenplumpython/type.py, tests/test_func.py
Previously, we implemented function calls with no argument, e.g.
`version()`, and function calls on constants, e.g. `add(1, 2)`. This
patch adds support for function calls on table columns, e.g.
`SELECT multiply(t.a, t.b) FROM t`. This makes the pandas-like API
more powerful.
=> Support function calls on table columns

greenplumpython/expr.py, tests/test_binaryExpr.py, tests/test_column.py, tests/test_unaryExpr.py
- Make table in test_binaryExpr.py temporary
- support not(), abs(), pos(), neg()
- Add tests
- TODO :
* Integrate unary operator in table.__getitem__
* Probably need to change how to do unary_operator_column name alias
=> Support Unary Operator on Column

greenplumpython/__init__.py, greenplumpython/expr.py, greenplumpython/func.py, greenplumpython/type.py, tests/test_func.py
Array functions take arrays as arguments. Before calling the
function, each attribute in the rows will be aggregated as an
array and passed to the function. In this way, the function can
have access to the attribute in all rows in the same call. This 
makes it possible for the user to do complex analytics and for
the PL handler to optimize the performance.
=> Support creating and calling array functions

greenplumpython/table.py, tests/test_const_table.py
During data analysis, users may want to select a slice of the table.
This patch supports slice selection without order on Greenplum
tables using "[]", and a function table.top() which supports a 
slice selection with an order defined by user.
=> Support get table on slice

concourse/pipeline/dev.yml, concourse/pipeline/job_def.lib.yml, concourse/pipeline/res_def.yml, concourse/scripts/entry.sh
1. support centos7 and ubuntu18 pipeline
2. change all `bin_gpdb_debug` to `bin_gpdb`
3. for the `plpyton3` install python3.9 reason need to install `pip` using `get-pip.py` for install tox and other requirements
=> feat: support centos7 and ubuntu18 for CI

tox.ini
This patch set Python base for running lint check to Python3.9
=> Set pythonbase for lint to python3.9

concourse/README.md, concourse/fly.sh
Concourse is deprecating some special characters in the pipeline name.
See details at https://concourse-ci.org/config-basics.html#schema.identifier
The pipelines will be named as:
<rel|pr|merge|dev>[_test].<project_name>[branch_name][.user_defined_postfix]
- Pipeline type 'release' is renamed to 'rel'
- Pipeline type 'commit' is renamed to 'merge'
- '_test' suffix will be added to pipeline type for pipeline debugging
- Instead of setting the whole name of pipeline, user can only set the
postfix.
Patch from https://github.com/pivotal/ip4r/pull/2
=> Scripts for new pipeline naming rules

doc/source/expr.rst, doc/source/notebooks/basic.ipynb, greenplumpython/expr.py, tests/test_binaryExpr.py
This patch overrides 3 arithmetic operators for `Expr`: add, sub and mul.
=> Override arithmetic operators for `Expr`

greenplumpython/table.py, tests/test_const_table.py
This patch fixes errors when `print(table)` for table's query has no results.
=> Fix error when displaying table with no results

greenplumpython/db.py, greenplumpython/row.py, greenplumpython/table.py, tests/test_const_table.py
`Table.assign()` with functions returning more than one column returns
a **string of list** containing all of these columns, which results in impossibility 
to access  column by key. This patch changes the format of return to a dictionary,
row of a composite type after `assign()` looks like:
`{"result": {"sub_field_1": smt, "sub_field_2": smt}}`
=> Assign func with composite type

doc/source/notebooks/GreenplumPython-abalone.ipynb, doc/source/notebooks/basic.ipynb, greenplumpython/db.py, greenplumpython/func.py, greenplumpython/group.py, greenplumpython/order.py, greenplumpython/row.py, greenplumpython/table.py, tests/test_builtin.py, tests/test_const_table.py, tests/test_func.py, tests/test_group.py, tests/test_order.py
When applying a function on the table, the user can only select returning columns, 
the `assign()` function keeps all of the columns of the table applied, which could bring
extra work to users. This patch supports `apply()` function which returns a Table
only with returning columns of UDF.
=> Resupport `apply()` function

.github/workflows/lint.yml
see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: deprecated set-output command

doc/source/config.rst, doc/source/modules.rst, greenplumpython/__init__.py, greenplumpython/config.py, greenplumpython/db.py, requirements-doc.txt, tests/test_db.py, tests/test_op.py, tox.ini
To understand the result of GreenplumPython, users could
want to investigate the SQL query sent by GreenplumPython
to the database. This patch adds a global method to set up the option "sql_on".
If "sql_on" is True, GreenplumPython will print the query in the output, 
otherwise not. The default value is False.
=> Feat: set up to display sql or not

greenplumpython/table.py, tests/test_binaryExpr.py, tests/test_join.py
This patch sets the default select columns of join to all. 
It removes also `Table.rename()` so the API can handle itself 
self join, the user doesn't need to handle rename Table.
=> Fix Join default select empty problem

requirements.txt
psycopg2 contains native code which needs to be build by GCC. however,
the python3 installed on CI is not in a standard directory, the include
path needs to be passed through CFLAGS. This has been addressed by #104.
Some unknown changes changed the version of setuptools being used by tox
to install psycopg2. The latest one doesn't seem to be working well with
CFLAGS. It is probably related to
https://github.com/pypa/setuptools/commit/bd7613f7921e8d60fa089d3ab419d0f04db6db6f
cc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -W
all -fPIC "-DPSYCOPG_VERSION=2.9.3 (dt dec pq3 ext lo64)" -DPSYCOPG_DEBUG=1 -DP
G_VERSION_NUM=90426 -DHAVE_LO64=1 -DPSYCOPG_DEBUG=1 -I/tmp/build/7ca3f3a1/green
plumpython_src/.tox/test_py39/include -I/opt/python-3.9.13/include/python3.9 -I
. …
=> Fix psycopg2 with CFLAGS

greenplumpython/table.py, tests/test_const_table.py
One row can contain `NULL` values, and it caused problem when we 
want to display the table, because `format()` function can't handle
`None` type. This patch fixes this problem by providing two scenarios:
* if `None` belong to a `list`: display None
* else: display empty
=> Fix Exception raised when result contains NULL

concourse/pipeline/res_def.yml
registry-image will cost less.
Add latest tag to work around the issue with
https://github.com/concourse/registry-image-resource/issues/327#issuecomment-1318504587
=> Use registry-image

greenplumpython/table.py, tests/test_const_table.py
Noticed that Zeros (0) are not shown in the actual state because __repr__ and _repr_html_ are using "if c" condition instead of "if c is not None"
=> fix: zeros representation in table

setup.py
For the last Beta release, the folder `builtin` containing a list of existing 
GreenpluPython aggregate functions was not included in the package. 
This patch fixes this bug.
=> Fix bultin folder not include bug

requirements-dev.txt, requirements-doc.txt, tox.ini
- Add tox target docstyle which uses pydocstyle to lint python doc
strings. See https://github.com/PyCQA/pydocstyle and
http://www.python.org/dev/peps/pep-0257/
'tox -e docstyle' will check all py files in greenplumpython
directory.
Use 'tox -e docstyle -- <path_to_the_py_file>' to lint individual py
source file.
- The doc linter has not been enabled on CI yet. It will be done in
another PR later.
=> Lint for python docstr

greenplumpython/func.py, requirements.txt
this pr fix can not run greenplumpython in python repl
see issue https://github.com/python/cpython/issues/57129
=> fix: can not run in Python repl

doc/source/notebooks/pandas.ipynb
- Typos and punctuations.
- Blank lines to make bullet work in markdown.
- Code changes due to API changes.
- Distinguish the dataframe in pandas and GrenplumPython by prefix,
`pdf` and `gdf`.
=> Doc modification for pandas comparison

doc/source/index.rst, doc/source/install.rst, doc/source/requirements.rst, greenplumpython/col.py, greenplumpython/dataframe.py, greenplumpython/db.py, greenplumpython/func.py, requirements.txt, setup.cfg, setup.py
As a dependency of GreenplumPython, psycopg2 is a source package. To install it, the client side 
need to have
* libpq and its C header files,
* C compilers, such as gcc
installed so that the C code in the psycopg2 package can be compiled. This can be complicated 
to handle different system environment, to sidestep this problem, we change our dependency to 
psycopg2-binary, which is a binary package.
This patch adds also more examples and explaination in documentation. And change the lowest python 
version requirement to Python3.9.
=> Change psycopg2 package to binary

greenplumpython/dataframe.py, tests/test_dataframe.py
Add 'with' storage_parameters options for save_as.
The AO table is more efficiency than heap for analytic usage, so `Greenplum Python` should have an option to create AO table.
=> add 'with' storage_parameters options for save_as

tox.ini
pycodestyle line length lint is used by pylsp.
Set it to the same number as black in pyproject.toml.
pycodestyle doesn't suport pyproject.toml, see
https://github.com/PyCQA/pycodestyle/issues/813
=> Set pycodestyle line length to 100

greenplumpython/builtins/functions.py, greenplumpython/col.py, greenplumpython/dataframe.py, greenplumpython/db.py, greenplumpython/expr.py, greenplumpython/func.py, greenplumpython/group.py, greenplumpython/order.py, greenplumpython/type.py, tests/test_binaryExpr.py, tests/test_column.py, tests/test_dataframe.py, tests/test_func.py
This patch removes redundant private `@property`. 
And fix type error of `_qualified_name`'s return type.
This patch removes also redundant attributes in class constructors
and methods.
=> Remove redundant attributes and property

doc/source/pd_df.rst, greenplumpython/pandas/dataframe.py
`:meta private:` can't follow a `.`
=> Fix pandas api doc

doc/source/notebooks/basic.ipynb
hyperlinks cannot be surrounded by backticks('`').
=> Fix doc typo

requirements.txt
Previously in `requirements.txt`, `psycopg2-binary==2.9.5`. 
This patch removes the strict version requirement and changes 
it to `2.9.*` to meet more possibility of versions.
=> Set psycopg2-binary version requirement not strict

greenplumpython/func.py, tests/test_func.py
Fix bugs when applying following functions: give constant to
a sub-functions: `Database is required to create type`.
```
df.assign(
func2=lambda t: func2(func1("a plane"))
)
```
=> Fix problem when args having no db when applying

greenplumpython/dataframe.py, tests/test_dataframe.py
This patch fixes the following issue when selecting an entire 
dataframe with slice doesn't contain a LIMIT clause in the query.
=> Fix select slice with [:]

greenplumpython/dataframe.py, tests/test_dataframe.py
Greenplum has a MPP architecture, so it relies on distribution 
of data across segments. This patch supports defining distribution 
type and distribution key of table when saving Dataframe to GPDB.
=> Add distribution key for saving dataframe in db

greenplumpython/experimental/embedding.py
Previously we set the vector modifier fix to 384. This patch
allows vector modifier to adjust the embedding dimension
if possible by extracting the appropriate information from 
the Sentence Transformer's `Models.Pooling` class, 
otherwise throwing an error.
=> Adapt vector modifier to model embedding dimension

greenplumpython/dataframe.py, tests/test_dataframe.py
So far, we don't have any information about the DataFrame's 
columns and their types. This patch supports retrieving column 
information of an existing table in the database. 
Moreover, adds a table check when creating a DataFrame from table, 
so that the user can catch the name error early.
=> Support Existing Table Column Information
